{% set name = "topologytoolkit" %}
{% set version = "0.9.9" %}
{% set build = 0 %}

{% set build = build + 100 %}   # [not TTK_WITH_PARAVIEW]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/topology-tool-kit/ttk/archive/{{ version }}.zip
  sha256: cdd8a2c3236b0cc6d332d4dd52cf0911ff3a2ab41ec4ea9fe3331a696a181963
  patches:
    - install_paths.patch
    - remove_linker_flags.patch
    - fix_ninja_build.patch  # [win]
    - boost_system.patch  # [win]
    - remove_rpaths.patch  # [linux]

build:
  number: {{ build }}
  skip: True  # [win and py27]

  # the package variant can be selected via the build string:
  # `conda install -c conda-forge "topologytoolkit * no_paraview*"` for vtk-variant
  # `conda install -c conda-forge "topologytoolkit * with_paraview*"` for paraview-variant (default)
  {% if TTK_WITH_PARAVIEW == "True" %}
  {% set paraview_prefix = "with_paraview" %}
  {% else %}
  {% set paraview_prefix = "no_paraview" %}
  {% endif %}
  string: {{ paraview_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

  # this de-prioritizes the non-paraview variant of the package and makes paraview the default
  track_features:
    - ttk_without_paraview  # [not TTK_WITH_PARAVIEW]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm-devel') }}  # [linux]
    - {{ cdt('libice-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - cmake
    - ninja  # [win]
    - clangdev  # [win]
  host:
    - python
    - openmp  # [win]    
    - paraview  # [TTK_WITH_PARAVIEW]
    - vtk ==9.0.1  # [not TTK_WITH_PARAVIEW]
    - tbb-devel
    - boost-cpp
    - zlib
    - graphviz  # [not win]
    - sqlite
    - zfp
    - eigen
    - spectralib
    - numpy
  run:
    - python
    - openmp  # [win]
    - paraview  # [TTK_WITH_PARAVIEW]
    - vtk ==9.0.1  # [not TTK_WITH_PARAVIEW]
    - zlib
    - graphviz  # [not win]
    - sqlite
    - zfp
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - topologytoolkit
  source_files:
    - examples/data/inputData.vtu
    - examples/python/example.py
  commands:
    - ldd "${PREFIX}/bin/ttkMorseSmaleComplexCmd"  # [linux]
    - readelf -d "${PREFIX}/bin/ttkMorseSmaleComplexCmd"  # [linux]
    - python examples/python/example.py examples/data/inputData.vtu
    - ttkMorseSmaleComplexCmd -i examples/data/inputData.vtu -o ""
    - pvpython examples/pvpython/example.py examples/data/inputData.vtu  # [TTK_WITH_PARAVIEW]

about:
  home: https://topology-tool-kit.github.io/
  license: BSD custom 5-clause variant
  license_family: BSD
  license_file: LICENSE
  summary: >
    The Topology ToolKit (TTK) is an open-source library and software
    collection for topological data analysis and visualization. 
  description: |
    TTK can handle scalar data defined either on regular grids or
    triangulations, in 2D, 3D, or more. It provides a substantial collection
    of generic, efficient and robust implementations of key algorithms in
    topological data analysis. It includes:
    · For scalar data: critical points, integral lines, persistence diagrams,
      persistence curves, merge trees, contour trees, Reeb graphs, Morse-Smale
      complexes, topological simplification, topology-aware compression,
      harmonic design;
    · For bivariate scalar data: fibers, fiber surfaces, continuous
      scatterplots, Jacobi sets, Reeb spaces;
    · For uncertain scalar data: mandatory critical points;
    · For time-varying scalar data: critical point tracking, nested tracking
      graphs;
    · For high-dimensional / point cloud data: dimension reduction,
      persistence-based clustering;
    · and more!

extra:
  recipe-maintainers:
    - lhofmann
    - julien-tierny
